### ISSUE TITLE
Non-selectable passed to select()

### ISSUE THREAD

**Issue by iAmGroute** [iAmGroute/NPTpy#4]
Trace:
```
... (many keepalives)
1568793504.496 [Portal.Link    ]        Sent                  5   Bytes
1568793504.497 [Portal.Link    ]            content: 0100000000
1568793504.498 [Portal.Link    ]        Sent                  5   Bytes
1568793504.499 [Portal.Link    ]            content: 0100000000
1568793511.769 [Portal.Link    ]        Received              5   Bytes
1568793511.770 [Portal.Link    ]            content: 0100000000
1568793513.801 [Portal.Link    ]        Received              5   Bytes
1568793513.801 [Portal.Link    ]            content: 0100000000
1568793514.887 [Portal.Link    ]        Sent                  5   Bytes
1568793514.888 [Portal.Link    ]            content: 0100000000
1568793514.889 [Portal.Link    ]        Sent                  5   Bytes
1568793514.890 [Portal.Link    ]            content: 0100000000
1568793525.391 [Portal.Link    ]        Sent                  5   Bytes
1568793525.392 [Portal.Link    ]            content: 0100000000
1568793525.393 [Portal.Link    ]        Sent                  5   Bytes
1568793525.394 [Portal.Link    ]            content: 0100000000
1568793535.892 [Portal.Link    ]        Sent                  5   Bytes
1568793535.893 [Portal.Link    ]            content: 0100000000
1568793535.895 [Portal.Link    ]        Sent                  5   Bytes
1568793535.895 [Portal.Link    ]            content: 0100000000
1568793546.356 [Portal.Link    ]        Sent                  5   Bytes
1568793546.357 [Portal.Link    ]            content: 0100000000
1568793546.358 [Portal.Link    ]        Sent                  5   Bytes
1568793546.359 [Portal.Link    ]            content: 0100000000
1568793556.831 [Portal.Link    ]        Sent                  5   Bytes
1568793556.832 [Portal.Link    ]            content: 0100000000
1568793556.833 [Portal.Link    ]        Sent                  5   Bytes
1568793556.834 [Portal.Link    ]            content: 0100000000
1568793561.024 [Portal.Link    ]        RX keepalive timeout
1568793561.028 [Portal.Link    ]            reconnecting
1568793561.028 [Portal.Link    ]        Stopping
1568793561.030 [Portal.Link    ]        Stopped
1568793561.030 [Portal.Link    ]        Stopping
1568793561.031 [Portal.Link    ]        Stopped
1568793561.035 [Portal.Portal  ]        Sent                 64   Bytes
1568793561.036 [Portal.Portal  ]            content: 01000000765432103030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030
1568793561.036 [Portal.Link    ]        RX keepalive timeout
1568793561.039 [Portal.Link    ]            disconnecting
1568793561.040 [Portal.Link    ]        Stopping
1568793561.041 [Portal.Link    ]        Stopped
1568793561.042 [Portal.Link    ]        Stopping
1568793561.042 [Portal.Link    ]        Stopped
1568793562.391 [Portal.Portal  ]        Received             39   Bytes
1568793562.391 [Portal.Portal  ]            content: 76302E316F70696F206C81D767869F38BB0172302E736572766572732E6E6574706F72742E696F
1568793562.396 [Portal.Link    ]        Starting
1568793562.397 [Portal.Link    ]        Started on         [0.0.0.0]:40361
1568793562.397 [Portal.Link    ]        Connecting to      [r0.servers.netport.io]:443
1568793562.456 [Portal.Link    ]            connected
1568793562.457 [Portal.Link    ]        Sent                 64   Bytes
1568793562.458 [Portal.Link    ]            content: 206C81D767869F383030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030
1568793562.501 [root]   argument must be an int, or have a fileno() method.
Traceback (most recent call last):
  File "portal.main.py", line 31, in <module>
    p.main()
  File "/NPTpy/NPTpy/Portal/Portal.py", line 69, in main
    readables, _, _         = select.select(rlist, [], [], 1) # Temporary
TypeError: argument must be an int, or have a fileno() method.
```

**Comment by iAmGroute** [comment]
Not valid after da516b26571177531ccaf4381a9f64e07d9dc844.
